SELECT
	BANCO.NOME AS 'BANCO',
	CONVENIO.VERBA AS 'VERBA',
	MIN(CONTRATO.DATA_INCLUSAO) AS 'DATA DE INCLUSÃO MAIS ANTIGO',
	MAX(CONTRATO.DATA_INCLUSAO) AS 'DATA DE INCLUSÃO MAIS NOVO',
	SUM(VALOR) AS 'SOMA DOS CONTRATOS'
FROM
	TB_CONTRATO CONTRATO
	LEFT JOIN TB_CONVENIO_SERVICO CONVENIOSERV ON CONTRATO.CONVENIO_SERVICO = CONVENIOSERV.CODIGO
	LEFT JOIN TB_CONVENIO CONVENIO ON CONVENIOSERV.CONVENIO = CONVENIO.CODIGO
	LEFT JOIN TB_BANCO ON CONVENIO.BANCO = BANCO.CODIGO
GROUP BY
	BANCO.NOME, CONVENIO.VERBA